[package]
name = "stack-num"
version = "1.12.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
regex = "0.1"
clap = "3.0"
nalgebra = "0.32.5"
